apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: boutique
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 876587216159.dkr.ecr.us-east-1.amazonaws.com/auth:f3a82ca7e0df3ee2a221d6f661d1935a95bcded8
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: AUTH_DB_URL

---

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: boutique
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
